### ISSUE TITLE
Error on trying to use GOLEM history

### ISSUE THREAD

**Issue by gkirgizov** [aimclub/FEDOT.Web#114]
Tried to upload the attached history to the server. Got following stacktrace:

```
Traceback (most recent call last):
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask_restx/api.py", line 673, in error_router
    return original_handler(f)
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask_restx/api.py", line 671, in error_router
    return self.handle_error(e)
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask_restx/api.py", line 673, in error_router
    return original_handler(f)
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask_restx/api.py", line 671, in error_router
    return self.handle_error(e)
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask_restx/api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/venv/lib/python3.8/site-packages/flask_accepts/decorators/decorators.py", line 206, in inner
    return func(*args, **kwargs)
  File "/nfshome/nnikitin/fedot-web/FEDOT.Web/app/api/showcase/controller.py", line 56, in post
    if case_meta_json['task'] == 'golem':
KeyError: 'task'


-->
 500
IMPORTANT! Save this url.
https://fedot.onti.actcognitive.org/ws/sandbox/custom_hist_tree_n50_trial048574067-67e1-49e6-8d07-1cee28931f46/history

Process finished with exit code 0
```

**Comment by Sash0check** [comment]
Looks like, you forget add 'task' field at case section. To add new history to the server you should send json like this:
```json
{
    "case": {
        "case_id": "new_case",
        "task": "golem",
        "metric_name": "roc_auc",
        "dataset_name": ""
    },
    "history": {
    }
}
```
